---
base_image_name: ubuntu-20.04-server-cloudimg-amd64.img
base_image_url: https://cloud-images.ubuntu.com/releases/focal/release/{{ base_image_name }}
base_image_sha: eb20cd25da5d2193283951953f6a0f5bdbd57474ac19fd1c36b9b77e6b68bbfc
libvirt_pool_dir: "/var/lib/libvirt/images"
vm_name_haproxy: haproxy
vm_name_master: master
vm_name_worker1: worker1
vm_name_worker2: worker2
vm_all_list: "{{ vm_name_haproxy + vm_name_master + vm_name_worker1 + vm_name_worker2 }}"
vm_master_vcpus: 2
vm_vcpus: 2
vm_ram_mb: 2048
vm_net: default
vm_root_pass: test123
cleanup_tmp: no
ssh_key: /root/.ssh/id_rsa.pub
